# -*- coding: utf-8 -*-
"""Breeze_ASR_26_FasterWhisper_台語轉錄器.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yfhtjR_DZrhBFL2HtLGyJPJEmCUPYn2Z

# 🇹🇼 台灣台語語音轉文字轉錄器 (Faster-Whisper 版)
## Breeze-ASR-26 × CTranslate2 加速推論

---

### 📌 功能特色
- ✅ **一鍵執行**：使用預轉換 CT2 模型，無需等待格式轉換
- 🇹🇼 **台語專用**：MediaTek Breeze-ASR-26 專為台灣台語 (Taiwanese Hokkien) 優化
- 🚀 **CTranslate2 加速**：比原版 HF Pipeline 快 2-4 倍，記憶體用量更低
- ⚡ **BatchedInferencePipeline**：利用 faster-whisper 批次推論進一步加速
- ⏱️ **精準時間戳記**：每段文字標註起始與結束時間
- 📺 **SRT 字幕輸出**：可選輸出標準 SRT 字幕格式
- 📊 **VAD 過濾**：Silero VAD 自動跳過靜音區段
- 🗣️ **台語轉漢字**：將台語語音轉錄為漢字（華語漢字）輸出

---
"""

# @title
# =============================================================================
# 台灣台語語音轉文字轉錄器 v8.0 (Faster-Whisper 直載版)
# 使用預轉換 CTranslate2 模型，免去格式轉換等待時間
# =============================================================================
# 版本: 8.0.0 (2026-04)
# 關鍵改進:
# 1. 直接載入預轉換 CT2 模型 (paulpengtw/faster-whisper-Breeze-ASR-26)
#    完全省去 ct2-transformers-converter 的 3-8 分鐘轉換等待。
# 2. 使用 Beam Search (beam_size=5) 提升辨識精確度。
# 3. BatchedInferencePipeline 批次推論 + Silero VAD 靜音過濾。
# 4. 依賴輕量化：不需安裝完整 transformers，只需 faster-whisper。
# =============================================================================

import os
import sys
import subprocess
import warnings
import time
import gc
import threading
import tempfile
import logging
from typing import Optional, Tuple, List
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from IPython.display import display, clear_output

warnings.filterwarnings("ignore")
logging.getLogger("faster_whisper").setLevel(logging.WARNING)
os.environ["TOKENIZERS_PARALLELISM"] = "false"
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

# =============================================================================
# 第一部分：環境設定
# =============================================================================

def install_dependencies():
    """安裝 faster-whisper (輕量依賴)"""
    print("📦 正在檢查並安裝依賴套件...")
    start_time = time.time()

    # 檢查 ffmpeg
    try:
        subprocess.run(["ffmpeg", "-version"], capture_output=True, check=True)
    except Exception:
        print("   📥 安裝 ffmpeg...")
        subprocess.run(["apt-get", "-y", "update", "-qq"], capture_output=True)
        subprocess.run(["apt-get", "-y", "install", "ffmpeg", "-qq"], capture_output=True)

    requirements = [
        "faster-whisper>=1.1.0",
        "pydub",
        "soundfile",
    ]

    print("   📥 校對 Python 套件版本...")
    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "--quiet", "--upgrade"] + requirements,
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
    )

    clear_output()
    print(f"✅ 依賴環境準備完成！(耗時 {time.time() - start_time:.1f} 秒)")

install_dependencies()

# =============================================================================
# 第二部分：匯入函式庫
# =============================================================================

import torch
import soundfile as sf
from pydub import AudioSegment
from faster_whisper import WhisperModel, BatchedInferencePipeline

try:
    from google.colab import files
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

print("✅ 所有核心函式庫載入成功！")

# =============================================================================
# 第三部分：資料結構定義
# =============================================================================

@dataclass
class TimestampedSegment:
    """帶時間戳記的轉錄片段"""
    start_time: float
    end_time: float
    text: str

    def format_time(self, seconds: float, srt_format: bool = False) -> str:
        if seconds is None or seconds < 0:
            seconds = 0.0
        hours = int(seconds // 3600)
        minutes = int((seconds % 3600) // 60)
        secs = seconds % 60
        if srt_format:
            return f"{hours:02d}:{minutes:02d}:{secs:06.3f}".replace('.', ',')
        else:
            return f"{hours:02d}:{minutes:02d}:{int(secs):02d}"

    def to_timestamp_line(self) -> str:
        start = self.format_time(self.start_time)
        end = self.format_time(self.end_time)
        return f"[{start} - {end}] {self.text}"

    def to_srt_block(self, index: int) -> str:
        start = self.format_time(self.start_time, srt_format=True)
        end = self.format_time(self.end_time, srt_format=True)
        return f"{index}\n{start} --> {end}\n{self.text}\n"

# =============================================================================
# 第四部分：GPU 偵測與最佳化
# =============================================================================

class GPUOptimizer:
    @staticmethod
    def detect() -> Tuple[str, str, int]:
        """回傳 (device, compute_type, batch_size)"""
        if not torch.cuda.is_available():
            print("⚠️ 未偵測到 GPU，使用 CPU 模式 (較慢)")
            return "cpu", "int8", 1

        gpu_name = torch.cuda.get_device_name(0)
        vram = torch.cuda.get_device_properties(0).total_memory / (1024**3)
        print(f"🔍 偵測到 GPU: {gpu_name} (VRAM: {vram:.1f} GB)")

        if vram >= 38:
            compute_type, batch_size = "float16", 24
        elif vram >= 22:
            compute_type, batch_size = "float16", 16
        elif vram >= 14:
            compute_type, batch_size = "float16", 8
        else:
            compute_type, batch_size = "int8_float16", 4

        print(f"✅ 配置: 精度={compute_type}, 批次量={batch_size}")
        return "cuda", compute_type, batch_size

# =============================================================================
# 第五部分：音檔轉換
# =============================================================================

class AudioConverter:
    TARGET_SR = 16000

    @staticmethod
    def convert(src_path: str) -> Tuple[str, float]:
        print("🔄 正在對齊音訊格式 (16kHz, 單聲道)...")
        start = time.time()

        fd, wav_path = tempfile.mkstemp(suffix=".wav")
        os.close(fd)

        cmd = [
            "ffmpeg", "-y", "-threads", str(os.cpu_count() or 4),
            "-i", src_path, "-ar", str(AudioConverter.TARGET_SR),
            "-ac", "1", "-c:a", "pcm_s16le", "-loglevel", "error", wav_path
        ]

        try:
            subprocess.run(cmd, check=True, capture_output=True)
        except subprocess.CalledProcessError:
            print("   ⚠️ ffmpeg 失敗，切換至 pydub...")
            audio = AudioSegment.from_file(src_path)
            audio = audio.set_frame_rate(AudioConverter.TARGET_SR).set_channels(1).set_sample_width(2)
            audio.export(wav_path, format="wav")

        try:
            duration = sf.info(wav_path).duration
        except Exception:
            duration = 0.0

        print(f"✅ 轉換完成！音檔長度: {duration:.1f} 秒 (耗時 {time.time() - start:.1f} 秒)")
        return wav_path, duration

# =============================================================================
# 第六部分：核心引擎 (直載預轉換 CT2 模型)
# =============================================================================

class BreezeASR:
    # 使用社群預轉換的 CTranslate2 模型，省去轉換等待
    MODEL_ID = "paulpengtw/faster-whisper-Breeze-ASR-26"

    def __init__(self, device: str, compute_type: str, batch_size: int):
        self.device = device
        self.compute_type = compute_type
        self.batch_size = batch_size
        self.model = None
        self.batched_model = None
        self._is_loaded = False
        self._load_status = "等待初始化"
        self._load_lock = threading.Lock()

    def load(self) -> 'BreezeASR':
        """載入預轉換的 CTranslate2 模型"""
        with self._load_lock:
            if self._is_loaded:
                return self
            try:
                self._load_status = "正在從 HuggingFace 下載 CT2 模型 (~2.9 GB)..."
                self.model = WhisperModel(
                    self.MODEL_ID,
                    device=self.device,
                    compute_type=self.compute_type,
                    cpu_threads=os.cpu_count() or 4,
                )

                self._load_status = "正在構建批次推論管線..."
                self.batched_model = BatchedInferencePipeline(model=self.model)

                self._is_loaded = True
                self._load_status = "載入完成"
            except Exception as e:
                self._load_status = f"載入失敗: {str(e)}"
                raise e
            return self

    def is_loaded(self) -> bool:
        return self._is_loaded

    def get_status(self) -> str:
        return self._load_status

    def transcribe(self, wav_path: str, use_vad: bool = True) -> List[TimestampedSegment]:
        """
        使用 BatchedInferencePipeline 進行批次轉錄。
        beam_size=5 提升辨識精確度 (與 HF Pipeline 的 Greedy Decoding 相比)。
        """
        print("\n🎤 啟動 Faster-Whisper 語音辨識引擎...")
        start_time = time.time()

        is_running = True

        def display_timer():
            while is_running:
                elapsed = int(time.time() - start_time)
                mins, secs = divmod(elapsed, 60)
                print(f"\r   ⏳ 引擎運算中... [{mins:02d}:{secs:02d}]", end="", flush=True)
                time.sleep(1)

        timer_thread = threading.Thread(target=display_timer)
        timer_thread.start()

        segments_out: List[TimestampedSegment] = []

        try:
            segments_iter, info = self.batched_model.transcribe(
                wav_path,
                batch_size=self.batch_size,
                language="zh",           # 強制指定中文，避免語言偵測開銷
                beam_size=5,             # Beam Search 提升精確度
                vad_filter=use_vad,
                vad_parameters=dict(
                    min_silence_duration_ms=500,
                    speech_pad_ms=200,
                ),
                word_timestamps=False,
                without_timestamps=False,
            )

            for seg in segments_iter:
                text = seg.text.strip()
                if not text:
                    continue
                start_t = seg.start if seg.start is not None else 0.0
                end_t = seg.end if seg.end is not None else start_t + 1.0
                segments_out.append(TimestampedSegment(
                    start_time=start_t,
                    end_time=end_t,
                    text=text
                ))

        finally:
            is_running = False
            timer_thread.join()
            print("\r" + " " * 50 + "\r", end="")

        elapsed = time.time() - start_time
        total_chars = sum(len(seg.text) for seg in segments_out)

        print(f"✅ 轉錄完成！")
        print(f"   偵測語言: {info.language} (機率 {info.language_probability:.2%})")
        print(f"   總計耗時: {elapsed:.1f} 秒")
        print(f"   產出片段: {len(segments_out)} 段")
        print(f"   總辨識字數: {total_chars} 字")

        return segments_out

# =============================================================================
# 第七部分：儲存結果
# =============================================================================

def save_transcript(segments: List[TimestampedSegment], src_name: str, output_srt: bool = True) -> Tuple[Optional[str], Optional[str]]:
    if not segments:
        print("\n⚠️ 轉錄結果為空，不建立檔案")
        return None, None

    base_dir = "/content" if IN_COLAB else os.getcwd()
    base_name = os.path.splitext(os.path.basename(src_name))[0]

    txt_path = os.path.join(base_dir, f"{base_name}_transcript.txt")
    with open(txt_path, "w", encoding="utf-8") as f:
        for segment in segments:
            f.write(segment.to_timestamp_line() + "\n")

    srt_path = None
    if output_srt:
        srt_path = os.path.join(base_dir, f"{base_name}_subtitle.srt")
        with open(srt_path, "w", encoding="utf-8") as f:
            for idx, segment in enumerate(segments, 1):
                f.write(segment.to_srt_block(idx) + "\n")

    print(f"\n💾 檔案已儲存：\n - [TXT] {txt_path}" + (f"\n - [SRT] {srt_path}" if srt_path else ""))
    return txt_path, srt_path

# =============================================================================
# 第八部分：主程式
# =============================================================================

def main(output_srt: bool = True):
    print("\n" + "="*65)
    print("🇹🇼 台灣台語語音轉文字轉錄器 v8.0 (Faster-Whisper 直載版)")
    print("   Powered by Breeze-ASR-26 × CTranslate2 × Beam Search")
    print("="*65)

    wav_path = None
    asr = None
    executor = None

    try:
        # 步驟 1: GPU 偵測
        print("\n[步驟 1/5] 硬體資源配置")
        device, compute_type, batch_size = GPUOptimizer.detect()

        # 步驟 2: 背景載入模型 + 等待上傳
        print("\n[步驟 2/5] 載入預轉換 CT2 模型 (首次需下載 ~2.9 GB)")
        asr = BreezeASR(device, compute_type, batch_size)
        executor = ThreadPoolExecutor(max_workers=2)
        model_future = executor.submit(asr.load)

        print("\n⚡ 系統正在背景下載並載入模型...")
        print("💡 請現在上傳您的台語音檔，兩者將並行處理！\n")

        if IN_COLAB:
            uploaded = files.upload()
            if not uploaded:
                print("❌ 操作取消：未選擇任何檔案。")
                return
            src_path = list(uploaded.keys())[0]
        else:
            src_path = input("請輸入音檔本機路徑: ")
            if not os.path.exists(src_path):
                print("❌ 錯誤：找不到該檔案。")
                return

        print(f"\n✅ 成功接收檔案: {src_path}")
        print(f"   目前模型狀態: {asr.get_status()}")

        # 步驟 3: 轉換音檔
        print("\n[步驟 3/5] 音檔前處理")
        wav_path, duration = AudioConverter.convert(src_path)

        # 步驟 4: 等待模型並轉錄
        print("\n[步驟 4/5] 語音辨識與時間戳對齊")
        if not asr.is_loaded():
            print("⏳ 正在等待模型載入...")
            while not asr.is_loaded():
                print(f"\r   狀態: {asr.get_status()}        ", end="", flush=True)
                time.sleep(1)
            print()

        model_future.result()
        segments = asr.transcribe(wav_path)

        # 步驟 5: 儲存與下載
        print("\n[步驟 5/5] 封裝與輸出")
        txt_path, srt_path = save_transcript(segments, src_path, output_srt)

        if txt_path and segments:
            print("\n" + "="*65)
            print("📝 轉錄結果預覽 (前 8 段)")
            print("="*65)
            for seg in segments[:8]:
                print(seg.to_timestamp_line())
            if len(segments) > 8:
                print(f"\n... (共 {len(segments)} 段，完整內容請參閱下載檔案) ...")
            print("="*65)

            if IN_COLAB:
                print("\n📥 正在觸發瀏覽器下載...")
                files.download(txt_path)
                if srt_path:
                    files.download(srt_path)

        print("\n✨ 任務圓滿完成，感謝您的使用！")

    except Exception as e:
        print(f"\n❌ 發生未預期的系統錯誤: {e}")
        import traceback
        traceback.print_exc()

    finally:
        if wav_path and os.path.exists(wav_path):
            try:
                os.remove(wav_path)
                print("\n🧹 已清理暫存音檔")
            except Exception:
                pass
        if executor:
            executor.shutdown(wait=False)
        if asr and asr.model:
            del asr.model
            del asr.batched_model
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        gc.collect()

if __name__ == "__main__":
    main(output_srt=True)